spring.application.name=promptdesk
spring.datasource.url=jdbc:mysql://localhost:3306/promptdesk
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port = 9096
openai.api.key=${OPENAI_API_KEY}
